#!/bin/bash
# create loadbalancer service
# create ingress yaml file as follow
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: nasr.project # add this domain to /etc/hosts if you don't have a domian
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-loadbalancer
            port:
              number: 8000
# install helm
curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
sudo apt-get install apt-transport-https --yes
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
# installing ingress controller using helm
helm repo add nginx-stable https://helm.nginx.com/stable
helm repo update
helm install nginx-ingress nginx-stable/nginx-ingress --set rbac.create=true
# whitelist ingress controller external ip (allow ingress for ingress load balancer ip address)
