apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-challenge
  name: my-loadbalancer
spec:
  ports:
  - nodePort: 30800
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: devops-challenge
  type: LoadBalancer

